version: '3.7'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://khem-postgres:khem-postgres@db/khem_fastapi_dev
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=khem-postgres
      - POSTGRES_PASSWORD=khem-postgres
      - POSTGRES_DB=khem_fastapi_dev

volumes:
  postgres_data:
